version: '3'

services:       
    jwtauthserver:
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - 8080:8080
    jwtauthdb:
        image: mysql
        ports: 
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=jwtauthserver
            - MYSQL_DATABASE=jwtauth
            - MYSQL_ROOT_HOST=%
           